export const types = {
  ADD_REPOSITORY_REQUEST: "repositories/ADD_REPOSITORY_REQUEST",
  ADD_REPOSITORY_SUCCESS: "repositories/ADD_REPOSITORY_SUCCESS",
  ADD_REPOSITORY_FAILURE: "repositories/ADD_REPOSITORY_FAILURE",
  FETCH_REPOSITORIES_REQUEST: "repositories/FETCH_REPOSITORIES_REQUEST",
  FETCH_REPOSITORIES_SUCCESS: "repositories/FETCH_REPOSITORIES_SUCCESS",
  FETCH_REPOSITORIES_FAILURE: "repositories/FETCH_REPOSITORIES_FAILURE",
  SET_REPOSITORY_DATA: "repositories/SET_REPOSITORY_DATA",
  DELETE_REPOSITORY: "repositories/DELETE_REPOSITORY"
};
